-- \

CREATE TABLE genders (
    genderId INT PRIMARY KEY AUTO_INCREMENT,
    genderName VARCHAR(50) NOT NULL
);

CREATE TABLE roles (
    roleId INT PRIMARY KEY AUTO_INCREMENT,
    roleName VARCHAR(50) NOT NULL
);

CREATE TABLE users (
    userId INT PRIMARY KEY AUTO_INCREMENT,
    fullname VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    date_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    date_updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    genderId INT,
    roleId INT,
    FOREIGN KEY (genderId) REFERENCES genders(genderId),
    FOREIGN KEY (roleId) REFERENCES roles(roleId)
) ENGINE=InnoDB;
